spring:
  profiles: prod
  cache:
    jcache:
      config: classpath:ehcache.xml
management:
  endpoints:
    web:
      exposure:
        include: "*"
bucket4j:
  enabled: true
  filters:
  - cache-name: buckets
    filter-method: servlet
    url: /*
    rate-limits:
    - filter-key-type: default
      bandwidths:
      - capacity: 10
        time: 1
        unit: minutes

---

spring:
  profiles: dev