management:
  endpoints:
    web:
      exposure:
        include: "**"

spring:
  profiles: prod
  cache:
      jcache:
        config: classpath:ehcache.xml

bucket4j:
  enabled: true
  filters:
    - cache-name: buckets
      url: /**
      rate-limits:
    - filter-key-type: default
      bandwidths:
      - capacity: 5
        time: 10
        unit: seconds


---

spring:
  profiles: dev